apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Tutoriales-App-Connect-Enterprise
  description: Tutoriales App Connect Enterprise
  annotations:
    github.com/project-slug: crlsquilumba/Tutoriales-App-Connect-Enterprise
    github.com/branch-count: "1"
    github.com/has-gitflow: "false"
    github.com/default-branch: "main"
  links:
    - url: https://github.com/crlsquilumba/Tutoriales-App-Connect-Enterprise/tree/main
      title: "✅ main — producción"
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
